global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "adhd_alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: 'mcp-adhd-server'
    metrics_path: '/api/monitoring/metrics/prometheus'
    scrape_interval: 10s
    scrape_timeout: 5s
    static_configs:
      - targets: ['host.docker.internal:8000']
    
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  
  - job_name: 'redis-exporter' 
    static_configs:
      - targets: ['redis-exporter:9121']
  
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['host.docker.internal:9187']